apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- kustomize-config.yml

resources:
- app-configmap.yaml
- app-deployment.yaml
- app-service.yaml
- db-deployment.yaml
- db-pvc.yaml
- db-service.yaml
- migration-job.yaml
