kind: Deployment
apiVersion: apps/v1
metadata:
  name: payment
  labels:
    app: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/microservices/payment
        name: queue-consumer
        envFrom:
          - configMapRef:
              name: rabbitmq-connection-credentials
        command: ["python", "-u", "payment.py"]
