apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources (shared amongst environments)
resources:
- ../../bases
- persistent-volume.yaml

images:
- name: image-registry.openshift-image-registry.svc:5000/microservices/delivery
  newName: k3d-microservices-registry:38597/microservices/delivery


patchesStrategicMerge:
- set-local-storage.yaml
